source('process_data.R')
source('plot1.R')
source('plot2.R')
source('plot3.R')
source('plot4.R')

data <- process.data('Data/household_power_consumption.txt', date.start='2007-02-01', date.stop='2007-02-02')
plot1(data)
plot2(data)
plot3(data)
plot4(data)